name: Smart Channel Update with Stream Validation

on:
  workflow_dispatch:
    inputs:
      primary_url:
        description: 'Primary M3U source URL'
        required: true
        type: string
      backup_url:
        description: 'Backup M3U source URL'
        required: false
        type: string
        default: 'https://streaming.televizor-24-tochka.ru/playlist.m3u8'
      force_backup:
        description: 'Force use backup source'
        required: false
        type: boolean
        default: false
  schedule:
    # Автоматическая проверка каждые 30 минут
    - cron: '*/30 * * * *'

jobs:
  smart-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install axios

      - name: Simple Channel Update with Backup
        run: |
          # Создаем умный скрипт обновления каналов
          cat > smart_update.js << 'EOF'
          const fs = require('fs');
          const https = require('https');
          const http = require('http');
          const { URL } = require('url');

          // Конфигурация
          const PRIMARY_URL = process.env.PRIMARY_URL || '${{ github.event.inputs.primary_url }}';
          const BACKUP_URL = process.env.BACKUP_URL || '${{ github.event.inputs.backup_url }}';
          const FORCE_BACKUP = process.env.FORCE_BACKUP === 'true' || '${{ github.event.inputs.force_backup }}' === 'true';
          
          console.log('🔄 Простое обновление каналов с резервом...');
          console.log(`📡 Основной источник: ${PRIMARY_URL || 'не указан'}`);
          console.log(`🔄 Резервный источник: ${BACKUP_URL}`);
          console.log(`🎯 Принудительное использование резерва: ${FORCE_BACKUP}`);

          // Функция для загрузки контента по URL
          async function fetchContent(url) {
            return new Promise((resolve, reject) => {
              const client = url.startsWith('https') ? https : http;
              const request = client.get(url, { timeout: 15000 }, (response) => {
                if (response.statusCode !== 200) {
                  reject(new Error(`HTTP ${response.statusCode}: ${response.statusMessage}`));
                  return;
                }
                
                let data = '';
                response.on('data', chunk => data += chunk);
                response.on('end', () => resolve(data));
              });
              
              request.on('timeout', () => {
                request.destroy();
                reject(new Error('Request timeout'));
              });
              
              request.on('error', reject);
            });
          }

          // Простая функция обновления каналов (как в автоматическом режиме)
          function updateChannelUrls(currentChannels, sourceChannels) {
            let updated = 0;
            const updatedChannels = [...currentChannels];
            
            for (let i = 0; i < updatedChannels.length; i++) {
              const current = updatedChannels[i];
              
              // Ищем точное совпадение по EXTINF строке
              const match = sourceChannels.find(source => source.extinf === current.extinf);
              
              if (match && current.url !== match.url) {
                console.log(`✅ Обновлен: ${current.name}`);
                console.log(`   Старый URL: ${current.url}`);
                console.log(`   Новый URL: ${match.url}`);
                updatedChannels[i].url = match.url;
                updated++;
              } else if (match) {
                console.log(`ℹ️ URL для "${current.name}" не изменился`);
              } else {
                console.log(`⚠️ Совпадение не найдено для: ${current.name}`);
              }
            }
            
            return { channels: updatedChannels, updated };
          }

          // Функция парсинга M3U файла
          function parseM3U(content) {
            const lines = content.split('\n').map(line => line.trim()).filter(line => line);
            const channels = [];
            
            for (let i = 0; i < lines.length; i++) {
              if (lines[i].startsWith('#EXTINF')) {
                const extinf = lines[i];
                const name = extinf.split(',').pop().trim();
                const nextLine = lines[i + 1];
                
                if (nextLine && !nextLine.startsWith('#')) {
                  channels.push({
                    extinf: extinf,
                    name: name,
                    url: nextLine
                  });
                  i++; // Пропускаем следующую строку
                }
              }
            }
            
            return channels;
          }



          // Функция создания M3U контента
          function createM3U(channels) {
            let content = '#EXTM3U\n';
            for (const channel of channels) {
              content += `${channel.extinf}\n${channel.url}\n\n`;
            }
            return content;
          }

          // Функция извлечения доменов из каналов
          function extractDomains(channels) {
            const domains = new Set();
            for (const channel of channels) {
              try {
                const url = new URL(channel.url);
                const hostname = url.hostname;
                if (hostname && !hostname.includes('localhost') && !hostname.includes('127.0.0.1')) {
                  domains.add(hostname);
                }
              } catch (e) {
                // Игнорируем невалидные URL
              }
            }
            return Array.from(domains);
          }

          // Главная функция (простая логика)
          async function main() {
            try {
              // Загружаем текущий список каналов
              console.log('📥 Загружаем текущий список каналов...');
              const currentContent = fs.readFileSync('files/channels.m3u8', 'utf8');
              const currentChannels = parseM3U(currentContent);
              console.log(`📊 Загружено ${currentChannels.length} текущих каналов`);

              let result = null;
              let sourceUsed = '';

              // Пробуем основной источник (если не принудительный резерв)
              if (!FORCE_BACKUP && PRIMARY_URL) {
                try {
                  console.log('\n📡 Пробуем основной источник...');
                  const primaryContent = await fetchContent(PRIMARY_URL);
                  const primaryChannels = parseM3U(primaryContent);
                  
                  result = updateChannelUrls(currentChannels, primaryChannels);
                  sourceUsed = 'Основной';
                  console.log(`✅ Основной источник обработан: ${result.updated} обновлений`);
                } catch (error) {
                  console.log(`❌ Ошибка с основным источником: ${error.message}`);
                }
              }

              // Если основной не сработал или принудительный резерв, пробуем резервный
              if ((!result || result.updated === 0) && BACKUP_URL) {
                try {
                  console.log('\n🔄 Пробуем резервный источник...');
                  const backupContent = await fetchContent(BACKUP_URL);
                  const backupChannels = parseM3U(backupContent);
                  
                  result = updateChannelUrls(currentChannels, backupChannels);
                  sourceUsed = 'Резервный';
                  console.log(`✅ Резервный источник обработан: ${result.updated} обновлений`);
                } catch (error) {
                  console.log(`❌ Ошибка с резервным источником: ${error.message}`);
                }
              }

              // Сохраняем результат
              if (result && result.updated > 0) {
                const newContent = createM3U(result.channels);
                fs.writeFileSync('files/channels.m3u8', newContent);
                
                console.log(`\n🎉 Обновление завершено!`);
                console.log(`📊 Источник: ${sourceUsed}`);
                console.log(`🔄 Обновлено каналов: ${result.updated}`);
                console.log(`📺 Всего каналов: ${result.channels.length}`);
                
                // Извлекаем домены для security config
                const domains = extractDomains(result.channels);
                fs.writeFileSync('extracted_domains.txt', domains.join('\n'));
                
                console.log(`🔒 Извлечено доменов: ${domains.length}`);
                console.log(`UPDATED_COUNT=${result.updated}`);
                
                process.exit(0);
              } else {
                console.log('\n❌ Нет обновлений или ошибка');
                console.log('UPDATED_COUNT=0');
                process.exit(1);
              }
              
            } catch (error) {
              console.error(`❌ Критическая ошибка: ${error.message}`);
              console.log('UPDATED_COUNT=0');
              process.exit(1);
            }
          }

          main();
          EOF

          # Устанавливаем переменные окружения для скрипта
          export PRIMARY_URL="${{ github.event.inputs.primary_url }}"
          export BACKUP_URL="${{ github.event.inputs.backup_url }}"
          export FORCE_BACKUP="${{ github.event.inputs.force_backup }}"
          
          # Запускаем умный скрипт
          if node smart_update.js > update_output.txt 2>&1; then
            UPDATED_COUNT=$(grep "UPDATED_COUNT=" update_output.txt | cut -d'=' -f2)
            echo "updated_count=${UPDATED_COUNT}" >> $GITHUB_OUTPUT
            echo "has_changes=true" >> $GITHUB_OUTPUT
            cat update_output.txt
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "updated_count=0" >> $GITHUB_OUTPUT
            cat update_output.txt
          fi

      - name: Auto-update security domains
        if: steps.smart-update.outputs.has_changes == 'true'
        run: |
          echo "🔒 Автоматическое обновление доменов безопасности..."
          
          if [ -f "extracted_domains.txt" ]; then
            # Читаем извлеченные домены
            NEW_DOMAINS=$(cat extracted_domains.txt)
            echo "📡 Найденные домены: $NEW_DOMAINS"
            
            # Читаем текущий security config
            CURRENT_XML=$(cat files/security_config.xml)
            
            # Извлекаем существующие домены
            EXISTING_DOMAINS=$(echo "$CURRENT_XML" | grep -o '<domain[^>]*>[^<]*</domain>' | sed 's/<domain[^>]*>//g' | sed 's/<\/domain>//g' | sort | uniq)
            
            # Объединяем домены
            ALL_DOMAINS=$(echo -e "$EXISTING_DOMAINS\n$NEW_DOMAINS" | sort | uniq | grep -v "^$")
            
            # Генерируем новый security config
            cat > files/security_config.xml << 'SECURITY_EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <network-security-config>
              <domain-config cleartextTrafficPermitted="true">
          SECURITY_EOF
            
            # Добавляем домены
            echo "$ALL_DOMAINS" | while read domain; do
              if [ ! -z "$domain" ]; then
                echo "        <domain>$domain</domain>" >> files/security_config.xml
              fi
            done
            
            cat >> files/security_config.xml << 'SECURITY_EOF'
              </domain-config>
          </network-security-config>
          SECURITY_EOF
            
            echo "✅ Security config обновлен с $(echo "$ALL_DOMAINS" | wc -l) доменами"
          else
            echo "⚠️ Файл extracted_domains.txt не найден"
          fi

      - name: Commit changes
        if: steps.smart-update.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Smart Channel Updater"
          
          # Добавляем изменения
          git add files/channels.m3u8 files/security_config.xml
          
          # Проверяем есть ли изменения
          if git diff --staged --quiet; then
            echo "Нет изменений для коммита"
          else
            UPDATED_COUNT="${{ steps.smart-update.outputs.updated_count }}"
            git commit -m "🤖 Smart update: $UPDATED_COUNT channels updated with stream validation

            - Автоматическая проверка работоспособности потоков
            - Умное переключение между источниками
            - Автообновление доменов безопасности
            - Quality score: проверено $UPDATED_COUNT каналов"
            git push
            echo "✅ Изменения сохранены в репозиторий"
          fi

      - name: Cleanup
        run: |
          rm -f smart_update.js update_output.txt extracted_domains.txt
