name: 🔧 Update Configuration

on:
  workflow_dispatch:
    inputs:
      service_available:
        description: 'Service Available'
        required: true
        default: true
        type: boolean
      maintenance_mode:
        description: 'Maintenance Mode'
        required: true
        default: false
        type: boolean
      message:
        description: 'Message for users'
        required: false
        default: ''
        type: string
      channels_version:
        description: 'Channels Version'
        required: true
        default: '5'
        type: string

jobs:
  update-config:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        
      - name: 🔧 Update configuration
        run: |
          # Читаем текущую конфигурацию
          CONFIG_FILE="api/config.json"
          
          # Создаем временный файл для обновления
          cat > temp_config.json << 'EOF'
          {
            "app_info": {
              "current_version": "1.0",
              "latest_version": "1.1",
              "version_code": 2,
              "download_url": "https://artemon4es.github.io/tv-channels-api/files/updates/app-v1.1.apk",
              "update_required": false,
              "changelog": "🔧 Добавлена система автообновления\n✨ Улучшена стабильность воспроизведения\n📱 Оптимизация для Android TV"
            },
            "service_config": {
              "service_available": ${{ github.event.inputs.service_available }},
              "message": "${{ github.event.inputs.message }}",
              "maintenance_mode": ${{ github.event.inputs.maintenance_mode }},
              "auth_required": true,
              "auth_endpoint": "https://api.github.com/user",
              "admin_mode": false
            },
            "channels_config": {
              "version": ${{ github.event.inputs.channels_version }},
              "last_updated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
              "url": "https://artemon4es.github.io/tv-channels-api/files/channels.m3u8",
              "security_config_url": "https://artemon4es.github.io/tv-channels-api/files/security_config.xml"
            },
            "api_info": {
              "version": "1.0",
              "last_updated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
              "security_note": "⚠️ Токены доступа НЕ хранятся в публичных файлах! Используйте безопасное хранение в приложении.",
              "endpoints": {
                "config": "/api/config.json",
                "channels": "/files/channels.m3u8",
                "security": "/files/security_config.xml"
              }
            }
          }
          EOF
          
          # Заменяем переменные даты
          sed -i "s/\$(date -u +%Y-%m-%dT%H:%M:%SZ)/$(date -u +%Y-%m-%dT%H:%M:%SZ)/g" temp_config.json
          
          # Форматируем JSON
          cat temp_config.json | jq '.' > $CONFIG_FILE
          
          # Удаляем временный файл
          rm temp_config.json
          
          echo "✅ Конфигурация обновлена"
          cat $CONFIG_FILE
        
      - name: 📝 Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api/config.json
          
          if git diff --staged --quiet; then
            echo "Нет изменений для коммита"
          else
            git commit -m "🔧 Update configuration
            
            Service Available: ${{ github.event.inputs.service_available }}
            Maintenance Mode: ${{ github.event.inputs.maintenance_mode }}
            Message: ${{ github.event.inputs.message }}
            Channels Version: ${{ github.event.inputs.channels_version }}
            
            Updated at: $(date -u +%Y-%m-%d\ %H:%M:%S\ UTC)"
            
            git push
            echo "✅ Изменения отправлены в репозиторий"
          fi
          
      - name: 🧪 Test API
        run: |
          echo "🧪 Тестирование API..."
          sleep 10  # Ждем обновления GitHub Pages
          
          # Тестируем основные endpoints
          curl -f "https://artemon4es.github.io/tv-channels-api/api/config.json" || echo "❌ Config endpoint failed"
          curl -f "https://artemon4es.github.io/tv-channels-api/files/channels.m3u8" || echo "❌ Channels endpoint failed"
          curl -f "https://artemon4es.github.io/tv-channels-api/files/security_config.xml" || echo "❌ Security endpoint failed"
          
          echo "✅ Тестирование завершено" 